In [3]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


In [5]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [6]:
train_dataset = pd.read_csv('/content/drive/MyDrive/train.csv')
test_dataset = pd.read_csv('/content/drive/MyDrive/test.csv')

In [7]:
train_dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [8]:
train_dataset = train_dataset[['Pclass', 'Sex', 'Age', 'Survived', 'SibSp', 'Parch', 'Fare']].copy()
test_dataset = test_dataset[['PassengerId', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']].copy()
train_dataset.head()

Pclass     Sex   Age  Survived  SibSp  Parch     Fare
0       3    male  22.0         0      1      0   7.2500
1       1  female  38.0         1      1      0  71.2833
2       3  female  26.0         1      0      0   7.9250
3       1  female  35.0         1      1      0  53.1000
4       3    male  35.0         0      0      0   8.0500

In [9]:
train_features = train_dataset.dropna()
train_labels = np.array(train_features.pop('Survived'))
print(train_labels)
train_features.head()

[0 1 1 1 0 0 0 1 1 1 1 0 0 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0
 0 1 1 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 1 1 0 1 0 1 1 0 1 0 0 0 0 0 0
 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0
 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1
 1 0 0 1 0 1 1 1 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 1 1 0 1 0 1 0 0 1 0 1 0 0
 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1
 0 0 1 0 0 0 1 0 1 0 1 1 1 1 0 0 0 0 0 1 0 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0
 1 1 1 0 1 1 1 0 0 0 0 1 1 0 1 1 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1
 0 0 0 0 1 0 0 0 1 1 0 1 0 0 1 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1
 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 1 1 1 1 0 0 1 1 0 1 1 0
 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 1
 1 1 0 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0 1 1 1 0 0 1 0 0 1 0 1 1 0 1 1 0 1 1
 1 0 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1
 1 0 0 1 0 0 1 0 0 1 1 0 

Pclass     Sex   Age  SibSp  Parch     Fare
0       3    male  22.0      1      0   7.2500
1       1  female  38.0      1      0  71.2833
2       3  female  26.0      0      0   7.9250
3       1  female  35.0      1      0  53.1000
4       3    male  35.0      0      0   8.0500

In [10]:
test_dataset.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare
0          892       3    male  34.5      0      0   7.8292
1          893       3  female  47.0      1      0   7.0000
2          894       2    male  62.0      0      0   9.6875
3          895       3    male  27.0      0      0   8.6625
4          896       3  female  22.0      1      1  12.2875

In [11]:
test_features = test_dataset.copy()
# keep passenger ids for later
test_pids = test_features.pop('PassengerId')
test_features.head()

Pclass     Sex   Age  SibSp  Parch     Fare
0       3    male  34.5      0      0   7.8292
1       3  female  47.0      1      0   7.0000
2       2    male  62.0      0      0   9.6875
3       3    male  27.0      0      0   8.6625
4       3  female  22.0      1      1  12.2875

In [12]:
age_mean = np.concatenate((
    np.array(train_features['Age'].dropna()),
    np.array(test_features['Age'].dropna())
)).mean()
print(age_mean)

29.881137667304014


In [13]:
test_features['Age'].isna().sum()

86

In [14]:
test_features['Age'].fillna(age_mean, inplace=True)
test_features['Age'].isna().sum()

0

In [15]:
test_features['Sex'].replace({ 'male': 0, 'female': 1 }, inplace=True)
train_features['Sex'].replace({ 'male': 0, 'female': 1 }, inplace=True)

<ipython-input-15-485a0d0a34a4>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_features['Sex'].replace({ 'male': 0, 'female': 1 }, inplace=True)


In [16]:
train_features.head()

Pclass  Sex   Age  SibSp  Parch     Fare
0       3    0  22.0      1      0   7.2500
1       1    1  38.0      1      0  71.2833
2       3    1  26.0      0      0   7.9250
3       1    1  35.0      1      0  53.1000
4       3    0  35.0      0      0   8.0500

In [17]:
normalizer = tf.keras.layers.Normalization(axis=-1)
normalizer.adapt(train_features)
print(normalizer(train_features[:10]))

tf.Tensor(
[[ 0.9112328  -0.7590513  -0.5303766   0.52457017 -0.5058951  -0.5189777 ]
 [-1.4763633   1.317434    0.5718312   0.52457017 -0.5058951   0.69189703]
 [ 0.9112328   1.317434   -0.25482464 -0.55170304 -0.5058951  -0.5062134 ]
 [-1.4763633   1.317434    0.36516726  0.52457017 -0.5058951   0.34804934]
 [ 0.9112328  -0.7590513   0.36516726 -0.55170304 -0.5058951  -0.5038497 ]
 [-1.4763633  -0.7590513   1.6740391  -0.55170304 -0.5058951   0.32464814]
 [ 0.9112328  -0.7590513  -1.9081364   2.6771166   0.6668618  -0.25754586]
 [ 0.9112328   1.317434   -0.18593666 -0.55170304  1.8396187  -0.44554418]
 [-0.28256524  1.317434   -1.0814805   0.52457017 -0.5058951  -0.08743458]
 [ 0.9112328   1.317434   -1.7703605   0.52457017  0.6668618  -0.34027746]], shape=(10, 6), dtype=float32)


In [18]:
model = tf.keras.Sequential([
    normalizer,
    tf.keras.layers.Dense(6, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid'),
])

In [19]:
model.predict(test_features[:10])

1/1 [==============================] - 0s 92ms/step


array([[0.50860184],
       [0.5833536 ],
       [0.50304824],
       [0.48378024],
       [0.5       ],
       [0.41582856],
       [0.50670344],
       [0.4238799 ],
       [0.47899354],
       [0.28118646]], dtype=float32)

In [20]:
model.compile(loss=tf.keras.losses.binary_crossentropy, optimizer='adam', metrics=['binary_accuracy'])

In [21]:
model.fit(train_features, train_labels,
          epochs=205, batch_size=64,
          use_multiprocessing=True, verbose=True)

Epoch 1/205
12/12 [==============================] - 1s 5ms/step - loss: 0.6442 - binary_accuracy: 0.6204
Epoch 2/205
12/12 [==============================] - 0s 8ms/step - loss: 0.6316 - binary_accuracy: 0.6723
Epoch 3/205
12/12 [==============================] - 0s 3ms/step - loss: 0.6201 - binary_accuracy: 0.6835
Epoch 4/205
12/12 [==============================] - 0s 3ms/step - loss: 0.6089 - binary_accuracy: 0.6849
Epoch 5/205
12/12 [==============================] - 0s 3ms/step - loss: 0.5990 - binary_accuracy: 0.6905
Epoch 6/205
12/12 [==============================] - 0s 3ms/step - loss: 0.5888 - binary_accuracy: 0.6989
Epoch 7/205
12/12 [==============================] - 0s 3ms/step - loss: 0.5795 - binary_accuracy: 0.7129
Epoch 8/205
12/12 [==============================] - 0s 3ms/step - loss: 0.5713 - binary_accuracy: 0.7269
Epoch 9/205
12/12 [==============================] - 0s 3ms/step - loss: 0.5631 - binary_accuracy: 0.7269
Epoch 10/205
12/12 [==========================

In [22]:
model.predict(test_features[:20])

1/1 [==============================] - 0s 55ms/step


array([[0.10382583],
       [0.44687256],
       [0.04754306],
       [0.1430133 ],
       [0.651893  ],
       [0.19858518],
       [0.5409384 ],
       [0.28845066],
       [0.5362375 ],
       [0.05156355],
       [0.13203739],
       [0.31318864],
       [0.9864689 ],
       [0.03888083],
       [0.9823794 ],
       [0.87191933],
       [0.10761509],
       [0.16504626],
       [0.46029633],
       [0.5900204 ]], dtype=float32)

In [23]:
predictions = model.predict(test_features)

14/14 [==============================] - 0s 2ms/step


In [24]:
survived = list(map(lambda p: int(p[0]>=0.5),predictions))
print((predictions > 0.5))
for s, p in zip(survived[:20], predictions[:20]):
    print(p, s)

[[False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [ True]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 

In [25]:
test_pids.head()

0    892
1    893
2    894
3    895
4    896
Name: PassengerId, dtype: int64

In [26]:
result = pd.DataFrame({
    'PassengerId': test_pids.array,
    'Survived': survived
})

result.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [29]:
result.to_csv('/content/drive/MyDrive/gender_submission.csv', index=False)